export default {
  id: 0,
  title: "The Balancing Act Between Labor and Capital: Why the World Feels so Crazy Right Now",
  shortTitle: "Balancing Labor vs. Capital",
  date: "Dec 7, 2024",
  readTime: "7 min read",
  type: "long",
  excerpt: "Since the dawn of agrarian civilization, human society has been shaped by an enduring struggle between labor and capital.",
  category: "Economics",
  coverImage: "/labor-capital-cover2.png", 
  content: `
    <p class="mb-8 font-serif text-xl leading-relaxed text-gray-800">Since the dawn of agrarian civilization, human society has been shaped by an enduring struggle between labor and capital. Each seeks to assert dominance over the other, yet their mutual dependence makes victory for either side impossible. Bound together by necessity, they are fated to wage this conflict endlessly — not to win, but simply to persist.</p>

    <h3 class="text-3xl font-serif text-stone-900 mt-16 mb-8 font-bold">The Balancing Act</h3>

    <p class="mb-8 text-gray-800 leading-relaxed">Human society is a vast web of interlinked variables, together forming a system of extraordinary complexity. Like a chemical reaction seeking equilibrium, this system constantly adjusts itself. When one variable shifts too far, disrupting the balance, the collective force of the other variables works to restore it.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">An example of this dynamic can be found in the perpetual struggle between labor and capital. Labor seeks higher wages for their work, but higher wages mean lower profits for businesses. Capital seeks higher returns on investment, but higher profits mean lower wages for the workforce.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">Despite their opposing goals, labor and capital remain deeply dependent on each other:</p>

    <ul class="list-disc pl-6 mb-8 space-y-4 marker:text-blue-800">
      <li>If labor becomes too strong, businesses will become unprofitable, forcing them to shut down. The very jobs that sustain workers' wages would disappear.</li>
      <li>If capital becomes too strong, workers will be unable to meet their basic needs. Without sufficiently good incentives, workers will stop working, destroying the ability of businesses to generate value.</li>
    </ul>

    <p class="mb-8 text-gray-800 leading-relaxed">This interdependence ensures that neither side can achieve total dominance without jeopardizing themselves in the process.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">However, real human society is far more complex than a simple balance between two variables. When one variable becomes unbalanced, it sets off a chain reaction, affecting countless other interconnected variables. This cascade of side effects ripples through society, trying its best to regain equilibrium.</p>

    <img src="/labor-capital-1.jpg" alt="Structural demographic trends showing the double spiral of popular well-being & elite overproduction" class="w-full rounded-lg mt-8 mb-2 shadow-md" />
    <p class="text-sm text-stone-500 mt-0 mb-8 text-center italic leading-normal">Structural demographic trends showing the double spiral of popular well-being & elite overproduction. Source: Peter Turchin (2009).</p>

    <h3 class="text-3xl font-serif text-stone-900 mt-16 mb-8 font-bold">Is Capital Winning the War Right Now?</h3>

    <p class="mb-8 text-gray-800 leading-relaxed">I believe that in the United States, the societal system is out of balance, and capital has grown too powerful. Below are key reasons why I believe this is the case:</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Stagnation of Real Wages</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">Since the 1970s, real wages in the U.S. have stagnated, even as real GDP has steadily grown. This implies that the wealth generated by increased production has been distributed to shareholders, not the workforce.</p>

    <img src="/labor-capital-2.jpg" alt="Comparison between the growth of real wages & real productivity of the manufacturing sector" class="w-full rounded-lg mt-8 mb-2 shadow-md" />
    <p class="text-sm text-stone-500 mt-0 mb-8 text-center italic leading-normal">Comparison between the growth of real wages & real productivity of the manufacturing sector. If such a trend was only present in the manufacturing sector, we could argue this is simply due to automation. However, a similar trend is present throughout all sectors of the workforce, except for the very top percentiles of earners. Source: Bureau of Labor Statistics (2020).</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Increase of the Numbers of Wealthy</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">Over the past 50 years, the number of decamillionaires per capita (adjusted for inflation) has skyrocketed. This confirms that the wealth generated from increased production has been disproportionately concentrated in the upper echelons of society.</p>

    <img src="/labor-capital-3.jpg" alt="Net worth of households, calculated in constant 1995 dollars" class="w-full rounded-lg mt-8 mb-2 shadow-md" />
    <p class="text-sm text-stone-500 mt-0 mb-8 text-center italic leading-normal">Net worth of households, calculated in constant 1995 dollars. Source: Wolff (2010)</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Women Entering the Workforce & Immigration</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">In recent decades, the labor supply has grown significantly, driven by the influx of women entering the workforce, as well as increased immigration. This surge in labor supply has far outpaced the growth in labor demand, exerting strong downward pressure on wages, as competition for jobs has grown.</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">High Demand for Degrees</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">As life becomes more challenging for the general populace, it's natural to expect people to seek upward mobility. This is exactly what we've seen, with demand for higher education soaring. More people than ever are pursuing degrees, while institutions have capitalized on this demand by charging exorbitant tuition fees.</p>

    <img src="/labor-capital-4.jpg" alt="Numbers of individuals earning the MBA degree" class="w-full rounded-lg mt-8 mb-2 shadow-md" />
    <p class="text-sm text-stone-500 mt-0 mb-8 text-center italic leading-normal">Numbers of individuals earning the MBA degree. Source: US Dept of Education.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">However, simply producing more graduates does not automatically create more jobs in their respective fields. As a result, an increasing number of graduates are forced to accept positions that should not require such an extensive education. Only a select few, the top performers, secure the roles they originally aspired to.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">This creates a large pool of well-educated, intelligent, and ambitious individuals who feel betrayed by a system that promised more than it delivered.</p>

    <img src="/labor-capital-5.jpg" alt="The distribution of reported incomes of law school graduates" class="w-full rounded-lg mt-8 mb-2 shadow-md" />
    <p class="text-sm text-stone-500 mt-0 mb-8 text-center italic leading-normal">The distribution of reported incomes of law school graduates. Source: NALP (2010).</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">High Polarization in Politics</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">As the number of wealthy individuals in the society has expanded, the proportion of people who belong to the elite has bloated. However, the number of seats in politics remains fixed, leading to intensified competition among elites for these coveted positions. As this competition grows, politicians are compelled to make increasingly grandiose promises and vilify their opponents, fueling a deeply polarized political climate.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">This polarized climate creates fertile ground for the rise of counter-elites. These are elites who failed to secure positions within the existing power structures, who along with the aforementioned unhappy elite-aspirants, seek to dismantle the system altogether through mobilizing the general populace in populist movements.</p>

    <h3 class="text-3xl font-serif text-stone-900 mt-16 mb-8 font-bold">Are We Living Through a Period of Correction?</h3>

    <p class="mb-8 text-gray-800 leading-relaxed">If the system is truly self-correcting, and capital has recently started to become too strong, we should see signs of it attempting to restore equilibrium. I believe this is the case. Below are some early signs of this:</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Indicators of Poor Wellbeing of the General Populace</h4>

    <ul class="list-disc pl-6 mb-8 space-y-4 marker:text-blue-800">
      <li>Low rates of marriage</li>
      <li>Low rates of childbirth</li>
      <li>High suicide rates</li>
      <li>High rates of mental illness</li>
    </ul>

    <p class="mb-8 text-gray-800 leading-relaxed">In this context, I want to highlight how these dynamics affect the labor supply. Childbirth has fallen to alarmingly low levels, which will ultimately lead to a shortage of new workers to replace retiring ones, a looming supply shock for the workforce. Additionally, rising rates of mental illness and suicide are further depleting the labor pool. Such supply shocks will eventually exert upwards pressure on wages, as firms compete over fewer employees.</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Sentiment Around Immigration is Turning</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">Immigration introduces an additional source of labor, effectively increasing the labor supply. Across much of the Western world, public sentiment is shifting toward a desire to close borders and limit this influx of labor. A move that would, again, place upwards pressure on wages.</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Rise of Alternative Currencies</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">Bitcoin is gaining ground. While much of its rise can be attributed to speculative gambling by a struggling populace seeking upward mobility, it's also undeniable that the true adoption of Bitcoin is growing at an exponential pace.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">For consumers (labor), a deflationary currency is advantageous, as it preserves purchasing power over time. In contrast, an inflationary government currency acts as a mechanism for wealth transfer, from ordinary people who hold the currency to those who can produce more of it at low cost, namely governments and banks. The owner class (capital) is less affected by this transfer, as inflation drives up asset prices, which the owner class are holders of.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">If labor must regain strength to restore equilibrium in the system, a shift toward a deflationary currency like Bitcoin makes logical sense.</p>

    <h3 class="text-3xl font-serif text-stone-900 mt-16 mb-8 font-bold">Why the World Feels Crazy</h3>

    <p class="mb-8 text-gray-800 leading-relaxed">The world feels chaotic because many long-running trends, some spanning for almost 80 years, are approaching a breaking point where reversal is inevitable. Our world is currently out of balance, and trying to trigger a return to equilibrium. Political instability is a symptom of this, and it seems many people are struggling to make sense of it.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">Donald Trump's rise to power is often misunderstood. While he certainly has a dedicated base of die-hard supporters, his election as President is not a result of people believing he is an exceptional individual, morally good, or even a particularly capable leader. Instead, he is a symbol for change.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">For much of the general populace, the existing power structure has failed them. Their quality of life is stagnating, or worse, declining, and this has gone on for too long. Faced with the status quo, many have chosen change, even with no guarantees it will be for the better. In Trump, whether their belief is misguided or not, they see a glimmer of hope.</p>

    <h3 class="text-3xl font-serif text-stone-900 mt-16 mb-8 font-bold">What's Next?</h3>

    <p class="mb-8 text-gray-800 leading-relaxed">For U.S. society to return to a healthy equilibrium, labor must regain strength in its struggle against capital. The exact path this process will take is impossible to predict, but one way or another, I believe it is bound to happen.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">I fear, based on historical patterns and the events unfolding around us, that the existing power structures will refuse to let go of their dominance. If that is the case, an escalation into violence is inevitable.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">In fact, recent events indicate a troubling trend toward societal unrest. The assassination of UnitedHealthcare CEO Brian Thompson in New York City has been met with widespread applause from the public rather than condemnation. This reaction reflects deep-seated frustration with the current political and economic systems. These grievances must be addressed — and quickly.</p>

    <h3 class="text-3xl font-serif text-stone-900 mt-16 mb-8 font-bold">How Does this Affect the Rest of the World?</h3>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">Global Geopolitics</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">On a broader geopolitical level, over recent decades we have witnessed an era of remarkable peace. Historically, such periods usually tend to occur when there is just a single dominant world power. The dominant power then proceeds to act as a global policeman, usually driven by a desire to secure the safety of its international trade routes. In recent history, the U.S. has acted in this role.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">However, with mounting domestic issues to address, it's reasonable to expect the U.S. to adopt a more isolationist foreign policy. At the same time, the rise of China challenges the U.S.'s hegemony as the sole dominant world power. Therefore, without a global policeman around, border disputes and territorial conflicts are likely to continue to become more frequent across the world.</p>

    <h4 class="text-2xl font-serif text-stone-800 mt-12 mb-6 italic">European Domestic Politics</h4>

    <p class="mb-8 text-gray-800 leading-relaxed">Here in Europe, while many of us mock Americans for electing a figure like Trump, we fail to recognize that our own societies are on a very similar trajectory. In Finland, wage stagnation began in the 1990s, so we could expect to be some 20 or so years behind the U.S. in the progression of our own 'labor vs. capital' cycle.</p>

    <p class="mb-8 text-gray-800 leading-relaxed">If nothing changes, we should brace ourselves for the rise of our own version of "Trumpism" in the coming decades, quietly watching ourselves descend into the very same madness we are currently laughing at. Alternatively, we could choose to learn from the mistakes of others. By urging our political and economic elite to voluntarily correct course, we might be able to avoid such a descent into madness altogether.</p>

    <p class="text-sm text-stone-500 mt-0 mb-8 text-center italic leading-normal">As a side note, I want to emphasize that the message above is apolitical. In my view, both the political right and the political left are guilty of pursuing shortsighted, self-serving policies. On both sides of the aisle, their actions seem more focused on placating their political bases to secure re-election, rather than pursuing policies aimed at the common good for all.</p>
  `
}